[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"
  # Environment variables are provided by GitHub Actions during build
  HUGGINGFACE_API_TOKEN = ""
  HUGGINGFACEALL = ""
  NEXTAUTH_SECRET = ""
  NODE_ENV = "production"

# Next.js serverless functions
[functions]
  directory = ".netlify/functions/"
  node_bundler = "esbuild"

# Essential plugin for Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

# API routes handling - this is crucial for Next.js API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# Fallback for all other routes to handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# GitHub Actions provides environment variables during build
# No Netlify environment variables needed (requires paid subscription)
# [build.environment]
#   NEXT_PRIVATE_TARGET = "serverless"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self'; connect-src 'self' https://api-inference.huggingface.co;"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"