[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Essential plugin for Next.js - this handles API routes automatically
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Functions configuration for Next.js App Router
[functions]
  directory = ".netlify/functions"
  node_bundler = "esbuild"

# API routes handling for Next.js App Router
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# Fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200